{ stdenv, symlinkJoin, lib, makeWrapper
, bundlerEnv
, ruby
, nodejs
, writeText
, nodePackages
, python3
, callPackage
, neovimUtils
, perl
, lndir
, vimPlugins
}:

neovim-unwrapped:

let
  # inherit interpreter from neovim
  lua = neovim-unwrapped.lua;

  wrapper = {
      extraName ? ""
    # passed as args but the binary. Can be either a string or list
    , wrapperArgs ? []
    # TODO throw ?
    , withPython2 ? false
    , withPython3 ? true
    # TODO deprecate
    # , python3Env ? python3
    # TODO should be suffixed 'Fn' ?
    , extraPython3Packages ? (_: [])

    # enable certain host providers
    , withNodeJs ? false
    , withPerl ? false
    , rubyEnv ? null

    # wether to create symlinks in $out/bin/vi(m) -> $out/bin/nvim
    , vimAlias ? false
    , viAlias ? false

    # additional argument not generated by makeNeovimConfig
    # it will append "-u <customRc>" to the wrapped arguments
    # set to false if you want to control where to save the generated config
    # (e.g., in ~/.config/init.vim or project/.nvimrc)
    , wrapRc ? true
    # vimL code that should be sourced as part of the generated init.lua file
    , neovimRcContent ? null
    # lua code to put into the generated init.lua file
    , luaRcContent ? ""
    # entry to load in packpath
    # , packpathDirs
    # expects a list of plugin configuration
    # expects { plugin=far-vim; config = "let g:far#source='rg'"; optional = false; }
    # just for tests
    , plugins ? [
        # vimPlugins.rocks-nvim
    ]
    /* the function you would have passed to lua.withPackages */
    , extraLuaPackages ? (_: [])

    # user viml configuration
    , customRC ? ""
    , ...
  }:
  assert withPython2 -> throw "Python2 support has been removed from the neovim wrapper, please remove withPython2 and python2Env.";


  stdenv.mkDerivation (finalAttrs: let
    # transform all plugins into an attrset
    # { optional = bool; plugin = package; }
    # pluginsNormalized = neovimUtils.normalizePlugins plugins;


    pluginRC = lib.foldl (acc: p: if p.config != null then acc ++ [p.config] else acc) []  finalAttrs.pluginsNormalized;

    # TODO get all dependencies
    myVimPackage = neovimUtils.normalizedPluginsToVimPackage finalAttrs.pluginsNormalized;

    packpathDirs.myNeovimPackages = myVimPackage;

    vimlRcContentWithPlugins = lib.optionalString (!isNull neovimRcContent) neovimRcContent
      + lib.concatStringsSep "\n" (pluginRC);

    rubyEnv = bundlerEnv {
      name = "neovim-ruby-env";
      gemdir = ./ruby_provider;
      postBuild = ''
        ln -sf ${ruby}/bin/* $out/bin
      '';
    };

    # TODO fix that
    # manifestRc = vimUtils.vimrcContent ({ customRC = ""; }) ;
    # a limited RC script used only to generate the manifest for remote plugins

    # manifestRc = "";

    finalPackdir = neovimUtils.packDir packpathDirs;

    rcContent = ''
      ${luaRcContent}
    ''
    # ou bien != ""
    + lib.optionalString (!isNull vimlRcContentWithPlugins) ''
      vim.cmd.source "${writeText "init.vim" vimlRcContentWithPlugins}"
    '';

    python3Env = python3Packages.python.withPackages (ps:
      [ ps.pynvim ]
      ++ (extraPython3Packages ps)
    #   ++ (lib.concatMap (f: f ps) pluginPython3Packages));
    );

    # getDeps = attrname: map (plugin: plugin.${attrname} or (_: [ ]));

    # requiredPlugins = vimUtils.requiredPluginsForPackage myVimPackage;
    # pluginPython3Packages = getDeps "python3Dependencies" requiredPlugins;

    wrapperArgsStr = if lib.isString wrapperArgs then wrapperArgs else lib.escapeShellArgs wrapperArgs;

    # providerLuaRc = neovimUtils.generateProviderRc {
    #   inherit withPython3 withNodeJs withPerl;
    #   withRuby = rubyEnv != null;
    # };

    # If configure != {}, we can't generate the rplugin.vim file with e.g
    # NVIM_SYSTEM_RPLUGIN_MANIFEST *and* NVIM_RPLUGIN_MANIFEST env vars set in
    # the wrapper. That's why only when configure != {} (tested both here and
    # when postBuild is evaluated), we call makeWrapper once to generate a
    # wrapper with most arguments we need, excluding those that cause problems to
    # generate rplugin.vim, but still required for the final wrapper.
    finalMakeWrapperArgs =
      [ "${neovim-unwrapped}/bin/nvim" "${placeholder "out"}/bin/nvim" ]
      ++ [ "--set" "NVIM_SYSTEM_RPLUGIN_MANIFEST" "${placeholder "out"}/rplugin.vim" ]
      ++ lib.optionals finalAttrs.wrapRc [ "--add-flags" "-u ${writeText "init.lua" rcContent}" ]
      ++ commonWrapperArgs
      ;

    perlEnv = perl.withPackages (p: [ p.NeovimExt p.Appcpanminus ]);

    # finalAttrs.
    luaEnv = let
      myFilter =  drv: builtins.trace "is ${drv.name} a vim plugin : "  (lib.debug.traceVal (!(drv.passthru?vimPlugin )));
    in
    # the wrapper already adds the interpreter to "paths"
    lua.withPackages(
      ps: (extraLuaPackages ps)
        # For now keep only those that are not vim plugins ?
        ++ (lib.filter myFilter finalAttrs.requiredLuaPlugins)
        # ++ [ (lua.pkgs.luaLib.toLuaModule lua) ]
      );

    ## Here we calculate all of the arguments to the 1st call of `makeWrapper`
    # We start with the executable itself NOTE we call this variable "initial"
    # because if configure != {} we need to call makeWrapper twice, in order to
    # avoid double wrapping, see comment near finalMakeWrapperArgs
    generatedWrapperArgs =
        let
          binPath = lib.makeBinPath (lib.optionals finalAttrs.withRuby [ rubyEnv ]
            ++ lib.optionals finalAttrs.withNodeJs [ nodejs ]);
  in
        [
          "--inherit-argv0"
        ] ++ lib.optionals finalAttrs.withRuby [
          "--set" "GEM_HOME" "${rubyEnv}/${rubyEnv.ruby.gemPath}"
        ] ++ lib.optionals (binPath != "") [
          "--suffix" "PATH" ":" binPath
        ]
        ++ lib.optionals (finalAttrs.requiredLuaPlugins != []) [
          # Assume for now it's good enough
          "--prefix" "LUA_PATH" ";" (lua.pkgs.luaLib.genLuaPathAbsStr luaEnv)
          "--prefix" "LUA_CPATH" ";" (lua.pkgs.luaLib.genLuaCPathAbsStr luaEnv)
        ]
        ;

    commonWrapperArgs = generatedWrapperArgs
      # ++ wrapperArgs
      # vim accepts a limited number of commands so we join them all
        ++ [

            "--add-flags" ''--cmd "lua ${finalAttrs.providerLuaRc}"''
            # (lib.intersperse "|" hostProviderViml)
          ] ++ lib.optionals ((packpathDirs.myNeovimPackages.start != [] || packpathDirs.myNeovimPackages.opt != [])) [
            "--add-flags" ''--cmd "set packpath^=${vimUtils.packDir packpathDirs}"''
            "--add-flags" ''--cmd "set rtp^=${vimUtils.packDir packpathDirs}"''
          ]
          ;

    pname = "neovim";
    version = lib.getVersion neovim-unwrapped;
  in {
      name = "${pname}-${version}${extraName}";
      inherit pname version;

      __structuredAttrs = true;
      dontUnpack = true;
      inherit viAlias vimAlias withNodeJs withPython3 withPerl;
      inherit wrapRc;
      inherit perlEnv;
      inherit python3Env rubyEnv ;
      withRuby = rubyEnv != null;
      inherit wrapperArgs generatedWrapperArgs;
      luaRcContent = rcContent;

      # Plugins requested by user
      plugins = plugins ++ [
        # vimPlugins.rocks-nvim
      ];
      # Plugins requested by user in normal form
      pluginsNormalized = neovimUtils.normalizePlugins finalAttrs.plugins;

      # TODO not only normalized, but with transitiveDeps
      requiredLuaPlugins = lua.pkgs.requiredLuaModules (map (x: x.plugin) finalAttrs.pluginsNormalized);

    # requiredLuaRocks = lib.filter luaLib.hasLuaModule
    #   (lua.pkgs.requiredLuaModules (self.nativeBuildInputs ++ self.propagatedBuildInputs));


      providerLuaRc = neovimUtils.generateProviderRc finalAttrs;
      # userRC
      inherit customRC;
      # error: cannot convert a function to JSON
      # inherit extraLuaPackages;

      # Remove the symlinks created by symlinkJoin which we need to perform
      # extra actions upon
      postBuild = lib.optionalString stdenv.hostPlatform.isLinux ''
        rm $out/share/applications/nvim.desktop
        substitute ${neovim-unwrapped}/share/applications/nvim.desktop $out/share/applications/nvim.desktop \
          --replace-warn 'Name=Neovim' 'Name=Neovim wrapper'
      ''
      + lib.optionalString finalAttrs.withPython3 ''
        makeWrapper ${finalAttrs.python3Env.interpreter} $out/bin/nvim-python3 --unset PYTHONPATH
      ''
      + lib.optionalString (finalAttrs.rubyEnv != null) ''
        ln -s ${finalAttrs.rubyEnv}/bin/neovim-ruby-host $out/bin/nvim-ruby
      ''
      + lib.optionalString finalAttrs.withNodeJs ''
        ln -s ${nodePackages.neovim}/bin/neovim-node-host $out/bin/nvim-node
      ''
      + lib.optionalString finalAttrs.withPerl ''
        ln -s ${finalAttrs.perlEnv}/bin/perl $out/bin/nvim-perl
      ''
      + lib.optionalString finalAttrs.vimAlias ''
        ln -s $out/bin/nvim $out/bin/vim
      ''
      + lib.optionalString finalAttrs.viAlias ''
        ln -s $out/bin/nvim $out/bin/vi
      ''
      # TODO ca c chelou
      # + lib.optionalString (manifestRc != null) (let
      + lib.optionalString true (let
        manifestWrapperArgs =
          [ "${neovim-unwrapped}/bin/nvim" "${placeholder "out"}/bin/nvim-wrapper" ] ++ commonWrapperArgs;
        in ''
        echo "Generating remote plugin manifest"
        export NVIM_RPLUGIN_MANIFEST=$out/rplugin.vim
        makeWrapper ${lib.escapeShellArgs manifestWrapperArgs} ${wrapperArgsStr}

        # Some plugins assume that the home directory is accessible for
        # initializing caches, temporary files, etc. Even if the plugin isn't
        # actively used, it may throw an error as soon as Neovim is launched
        # (e.g., inside an autoload script), causing manifest generation to
        # fail. Therefore, let's create a fake home directory before generating
        # the manifest, just to satisfy the needs of these plugins.
        #
        # See https://github.com/Yggdroot/LeaderF/blob/v1.21/autoload/lfMru.vim#L10
        # for an example of this behavior.
        export HOME="$(mktemp -d)"
        # Launch neovim with a vimrc file containing only the generated plugin
        # code. Pass various flags to disable temp file generation
        # (swap/viminfo) and redirect errors to stderr.
        # Only display the log on error since it will contain a few normally
        # irrelevant messages.
        if ! $out/bin/nvim-wrapper \
          -i NONE -n \
          -V1rplugins.log \
          +UpdateRemotePlugins +quit! > outfile 2>&1; then
          cat outfile
          echo -e "\nGenerating rplugin.vim failed!"
          exit 1
        fi
        rm "${placeholder "out"}/bin/nvim-wrapper"
      '')
      + ''
        rm $out/bin/nvim
        touch $out/rplugin.vim

        echo "Looking for lua dependencies..."
        source ${lua}/nix-support/utils.sh

        _addToLuaPath "${finalPackdir}"

        echo "LUA_PATH towards the end of packdir: $LUA_PATH"

        makeWrapper ${lib.escapeShellArgs finalMakeWrapperArgs} ${wrapperArgsStr} \
            --prefix LUA_PATH ';' "$LUA_PATH" \
            --prefix LUA_CPATH ';' "$LUA_CPATH"
      '';
          # --prefix PATH ':' "$program_PATH" \
          # --prefix LUA_PATH ';' "$LUA_PATH" \
          # --prefix LUA_CPATH ';' "$LUA_CPATH"

    buildPhase = ''
      runHook preBuild
      mkdir -p $out
      for i in ${neovim-unwrapped}; do
        lndir -silent $i $out
      done
      runHook postBuild
    '';

    preferLocalBuild = true;

    nativeBuildInputs = [ makeWrapper lndir ];

    doCheck = false;
    checkPhase = ''
      # check the generated init file is valid
      echo "RUNNING CHECKS"
      # ${placeholder "out"}/bin/nvim --headless -c "quit"
    '';
    passthru = {
      inherit (finalAttrs) providerLuaRc; # todo inherit main one
      unwrapped = neovim-unwrapped;
      initRc = neovimRcContent;

      tests = callPackage ./tests {
      };
    };

    meta = {
      inherit (neovim-unwrapped.meta)
        description
        longDescription
        homepage
        mainProgram
        license
        maintainers
        platforms;

      # To prevent builds on hydra
      hydraPlatforms = [];
      # prefer wrapper over the package
      priority = (neovim-unwrapped.meta.priority or lib.meta.defaultPriority) - 1;
    };
  });
in
  lib.makeOverridable wrapper
